### ISSUE TITLE
Crash when running on iOS14

### ISSUE THREAD

**Issue by osunnarvik** [IBM-Security/verify-sdk-ios#1]
When scanning an OnPremiseScan, I get a crash when calling 
AuthenticatorContext.shared.create(from: scanResult) when running on a device with iOS14
The QR in question has the flag "ignoreSslCerts" set true for testing purposes.

I have tried using the IBMVerify app as well for the same QR code, and that one also results in a crash. I dont have a proper stack-trace to provide, but it looks like the crash is happening in the thread com.apple-NSURLSession-delegate.

I am using XCode 12.0.1, and I have tried running on a device with iOS 12.4.5 installed. On iOS 12.4.5 it does not crash, so it looks like it is related to iOS14

Can you please investigate this?

**Comment by osunnarvik** [comment]
I was using version 2.0.6 of the IBMVerify SDK. I just now noticed a recent update of the SDK. I will try with this update to see if the problem is fixed.

**Comment by osunnarvik** [comment]
I tried updating the SDK to version 2.1.1 with the same result. Still crashes

**Comment by craigaps** [comment]
@osunnarvik sorry it's taken a while to come back to you on this issue.

Admittedly I wasn't able to reproduce the issue until I was on a VPN, but a changes were implemented for handling self-signed certificate in `URLSessionDelegate` in version [v2.1.2](https://github.com/IBM-Security/verify-sdk-ios/blob/master/CHANGELOG.md).  Are you able to re-test and confirm if the problem still exists for you?

**Comment by chagemann** [comment]
Closed due to inactivity.
